# This workflows will upload a Python Package using Twine when a release is created
# For more information see: 
#     https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [ published ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Upgrade tooling
      run: |
        python3 -m pip install --upgrade pip
        pip3 install --upgrade build setuptools setuptools_scm[toml] twine wheel
    - name: Build package
      run: |
        python3 -m build --wheel
        python3 setup.py sdist --format=zip
    - name: Store package
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distribution
        path: dist/

  release:
    runs-on: ubuntu-latest
    environment:
      name: release
    permissions:
      id-token: write  # mandatory for trusted publishing
    steps:
    - name: Retrieve package
      uses: actions/download-artifact@v4
      with:
        name: python-package-distribution
        path: dist/
    - name: Publish package (PyPi)
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://pypi.org/p/exotic  # for testing sub https://test.pypi.org/legacy/
